[tool.black]
line-length = 100
target-version = ["py311"]
include = '^.+\.pyi?$'
skip_magic_trailing_comma = true
extend-exclude = '''
(
    .*\.local.*
    | .*\.idea.*
    | .*\.vscode.*
    | migrations
)
'''


[tool.isort]
force_sort_within_sections = true
lines_after_imports = 2
known_third_party = "django"
known_django = "django"
default_section = "THIRDPARTY"
combine_as_imports = true
multi_line_output = 5
profile = "django"
skip = [".local", "migrations"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]


[tool.mypy]
cache_dir = ".local/mypy/"
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
exclude = [".local/*", "migrations"]
files = ["."]
no_implicit_optional = true
pretty = true
python_version = "3.11"
show_error_context = true
sqlite_cache = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
ignore_missing_imports = true
